title: Haobo Xu's Homepage
page-top-title: Haobo Xu
top-section-bg-text: Image & Video Generation · Diffusion Models
home-subtitle: Haobo Xu&ensp;|&ensp;徐浩博
copyright-text: '&copy; Haobo Xu 2026. All Rights Reserved.'
